/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CashierController;
import Controller.ManagerController;
import Model.ManagerModel;
import com.mysql.cj.protocol.Resultset;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kidurshalini
 */
public class CreateAccount1 extends javax.swing.JInternalFrame {

    ManagerModel ManagerModel = new ManagerModel();
    ManagerController manager;
    CashierController cashier;
    Connection con = null;
    PreparedStatement pstmt = null;

    String SUrl = "jdbc:MySQL://localhost:3306/stock_management_system";
    String SUser = "root";
    String SPass = "";

    String Firstname = ManagerModel.getFName();
    String Lastname = ManagerModel.getLName();
    String pass, Ads, Email, National, Gender, cashierid, id,type;
    int Phone = ManagerModel.getPhone();

    
              
        
    
    /**
     * Creates new form CreateAccount1
     */
    public CreateAccount1() {
        initComponents();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ui.setEastPane(null);
        ui.setSouthPane(null);
        ui.setWestPane(null);
        cashier = new CashierController(this);
        manager = new ManagerController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CAclear = new javax.swing.JButton();
        CAupdate = new javax.swing.JButton();
        CAadd = new javax.swing.JButton();
        CAsearch = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Cashier = new javax.swing.JCheckBox();
        Manager = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        Manager1 = new javax.swing.JRadioButton();
        Cashier1 = new javax.swing.JRadioButton();
        Password = new javax.swing.JTextField();
        Nid = new javax.swing.JTextField();
        Eid = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        P_no = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        passlbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1075, 701));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(1070, 690));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Phone number:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Last Name:");

        FName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Address.setRows(5);
        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(Address);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Type:");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Firstname", "Lastname", "Password", "Address", "National_Id", "Email_Id", "Phone_no"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(102, 102, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(60);
        }

        CAclear.setBackground(new java.awt.Color(255, 204, 204));
        CAclear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CAclear.setForeground(new java.awt.Color(255, 51, 51));
        CAclear.setText("CLEAR");
        CAclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAclearActionPerformed(evt);
            }
        });

        CAupdate.setBackground(new java.awt.Color(255, 255, 255));
        CAupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CAupdate.setForeground(new java.awt.Color(0, 0, 102));
        CAupdate.setText("UPDATE");
        CAupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAupdateActionPerformed(evt);
            }
        });

        CAadd.setBackground(new java.awt.Color(255, 255, 255));
        CAadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CAadd.setForeground(new java.awt.Color(0, 0, 102));
        CAadd.setText("ADD ");
        CAadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAaddMouseClicked(evt);
            }
        });
        CAadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAaddActionPerformed(evt);
            }
        });

        CAsearch.setBackground(new java.awt.Color(255, 255, 255));
        CAsearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CAsearch.setForeground(new java.awt.Color(0, 0, 102));
        CAsearch.setText("SEARCH");
        CAsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAsearchActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("First Name:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Address:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("National id No:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Email id:");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Cashier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cashier.setText("Cashier");
        Cashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierActionPerformed(evt);
            }
        });

        Manager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Manager.setText("Manager");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Password");

        Manager1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Manager1.setText("Manager");
        Manager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager1ActionPerformed(evt);
            }
        });

        Cashier1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cashier1.setText("Cashier");
        Cashier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cashier1ActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Nid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Nid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NidActionPerformed(evt);
            }
        });

        Eid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Eid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EidActionPerformed(evt);
            }
        });

        LName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });

        P_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        P_no.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_noActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("ID:");

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        passlbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        passlbl.setForeground(new java.awt.Color(204, 0, 0));

        emaillbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CAadd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel11)
                        .addComponent(jLabel20)
                        .addComponent(jLabel15)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(CAupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(CAclear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Eid, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(65, 65, 65)
                                            .addComponent(jLabel2)
                                            .addGap(48, 48, 48)
                                            .addComponent(LName))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                            .addComponent(P_no, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passlbl)
                                            .addComponent(emaillbl))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Manager)
                                .addGap(60, 60, 60)
                                .addComponent(Cashier)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Manager1)
                        .addGap(50, 50, 50)
                        .addComponent(Cashier1)
                        .addGap(75, 75, 75)
                        .addComponent(CAsearch)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel2)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(P_no, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(passlbl))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Nid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Eid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillbl))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Manager)
                    .addComponent(Cashier))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CAadd)
                    .addComponent(CAupdate)
                    .addComponent(CAclear))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manager1)
                    .addComponent(Cashier1)
                    .addComponent(CAsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void CashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashierActionPerformed

    private void CAclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAclearActionPerformed

        txtid.setText("");
        FName.setText("");
        LName.setText("");
        Password.setText("");
        Address.setText("");
        Eid.setText("");
        P_no.setText(" ");
        Nid.setText("");
        Cashier.setSelected(false);
        Manager.setSelected(false);

    }//GEN-LAST:event_CAclearActionPerformed


    private void CAupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAupdateActionPerformed
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);
            id = txtid.getText();
            Firstname = FName.getText();
            Lastname = LName.getText();
            pass = Password.getText();
            Ads = Address.getText();
            Email = Eid.getText();
               if (Cashier.isSelected()) {
                            type = "Cashier";
                        } else {
                            type = "manager";
                        }
            String phoneNumberString = P_no.getText().replaceAll("[^0-9]", "");
            if (phoneNumberString.length() == 10) {
                Phone = Integer.parseInt(phoneNumberString);
            }
            National = Nid.getText();

            String query = "UPDATE user SET U_ID=?,Type=?,First_Name=?,Last_Name=?,Password=?,Address=?,National_ID=?,Email_ID=?,Phone_no=? WHERE U_ID=?";

            pstmt = con.prepareStatement(query);
            pstmt.setString(1, id);
            pstmt.setString(1, type);
            pstmt.setString(2, Firstname);
            pstmt.setString(3, Lastname);
            pstmt.setString(4, pass);
            pstmt.setString(5, Ads);
            pstmt.setString(6, National);
            pstmt.setString(7, Email);
            pstmt.setInt(8, Phone);
            pstmt.setString(9, id);
            int rowsUpdate = pstmt.executeUpdate();


            // Check the result for each query
            if (rowsUpdate > 0) {
                JOptionPane.showMessageDialog(null, "Succussfullt Updated");
            } else {
                JOptionPane.showMessageDialog(null, "No record found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_CAupdateActionPerformed

    private void CAaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAaddActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);

            Firstname = FName.getText();
            Lastname = LName.getText();
            pass = Password.getText();
            Ads = Address.getText();
            Email = Eid.getText();
            String phoneNumberString = P_no.getText().replaceAll("[^0-9]", "");
            National = Nid.getText();
            if (Firstname.equals("") || pass.equals("") || Email.equals("")) {
                JOptionPane.showMessageDialog(null, "Fields can't be empty");
            } else {
                if (phoneNumberString.length() == 10) {
                    Phone = Integer.parseInt(phoneNumberString);

                    if (Cashier.isSelected() && Manager.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Can't select Manager and Cashier");
                        Cashier.setSelected(false);
                        Manager.setSelected(false);
                    } else {
                        if (Cashier.isSelected()) {
                            type = "Cashier";
                        } else {
                            type = "manager";
                        }
                    }
                    if (manager.isValidPassword(pass)) {

                        if (manager.isValidEmail(Email)) {
                            String id = manager.generateID();
                            String query = "INSERT INTO user(U_ID,Type,First_Name,Last_Name,Password,Address,National_ID,Email_id,Phone_no)VALUES(?,?,?,?,?,?,?,?,?)";
                            pstmt = con.prepareStatement(query);

                            pstmt.setString(1, id);
                            pstmt.setString(2, type);
                            pstmt.setString(3, Firstname);
                            pstmt.setString(4, Lastname);
                            pstmt.setString(5, pass);
                            pstmt.setString(6, Ads);
                            pstmt.setString(7, National);
                            pstmt.setString(8, Email);
                            pstmt.setInt(9, Phone);

                            pstmt.executeUpdate();

                            FName.setText("");
                            LName.setText("");
                            Password.setText("");
                            Address.setText("");
                            Eid.setText("");
                            P_no.setText(" ");
                            Nid.setText("");
                            passlbl.setText("");
                            emaillbl.setText("");
                            Cashier.setSelected(false);
                             Manager.setSelected(false);
                            JOptionPane.showMessageDialog(null, "Successfully Account created");

                        } else {
                            passlbl.setText("Password should be 8 values and use characters,numbers");

                        }}else {
                           emaillbl.setText("Email should be inclued @gmail.com");
                        }

                    
                } else {

                    JOptionPane.showMessageDialog(null, "Phone number must be 10 digits long.");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "This email id already used");
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_CAaddActionPerformed

    private void CAaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAaddMouseClicked

    }//GEN-LAST:event_CAaddMouseClicked

    private void CAsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAsearchActionPerformed
             
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);
              Statement st = con.createStatement();
                String sql;
            if (Cashier1.isSelected()) {
              sql = "select * from user where type='cashier'";
            } else{
              sql = "select * from user where type='manager'";          
            }            
                ResultSet rs = st.executeQuery(sql);
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.setRowCount(0);
                while (rs.next()) {

                    id = String.valueOf(rs.getString("U_ID"));
                    type = rs.getString("Type");
                    Firstname = rs.getString("First_Name");
                    Lastname = rs.getString("Last_Name");
                    pass = rs.getString("Password");;
                    Ads = rs.getString("Address");
                    National = rs.getString("National_ID");
                    Email = rs.getString("Email_id");
                    String Phone = rs.getString("Phone_no");
                    String tbData[] = {id,type, Firstname, Lastname, pass, Ads, National, Email, Phone};

                    tblModel.addRow(tbData);

                }
            
        } catch (Exception e) {
            System.out.println("Error! " + e.getMessage());
        }
 
    }//GEN-LAST:event_CAsearchActionPerformed

    private void Manager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager1ActionPerformed

    private void Cashier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cashier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cashier1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void NidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NidActionPerformed

    private void EidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EidActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void P_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_noActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        txtid.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        FName.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
        LName.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
        Password.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
        Address.setText(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
        Nid.setText(model.getValueAt(jTable1.getSelectedRow(), 5).toString());
        Eid.setText(model.getValueAt(jTable1.getSelectedRow(), 6).toString());
        P_no.setText(model.getValueAt(jTable1.getSelectedRow(), 7).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JButton CAadd;
    private javax.swing.JButton CAclear;
    private javax.swing.JButton CAsearch;
    private javax.swing.JButton CAupdate;
    private javax.swing.JCheckBox Cashier;
    private javax.swing.JRadioButton Cashier1;
    private javax.swing.JTextField Eid;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField LName;
    private javax.swing.JCheckBox Manager;
    private javax.swing.JRadioButton Manager1;
    private javax.swing.JTextField Nid;
    private javax.swing.JTextField P_no;
    private javax.swing.JTextField Password;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel passlbl;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

}
