/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Kidurshalini
 */
public class ManagerUI extends javax.swing.JFrame {

    /**
     * Creates new form ManagerUI
     */
     Color DefaultColor,ClickedColor;
    public ManagerUI() {
        initComponents();
          DefaultColor=new Color(255,255,255);
        ClickedColor=new Color(204,204,204);
        
        //set defult color to text on run time
        Createaccount.setBackground(DefaultColor);
        SearchM.setBackground(DefaultColor);
        Addproduct.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanal10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Createaccount = new javax.swing.JPanel();
        Account = new javax.swing.JLabel();
        SearchM = new javax.swing.JPanel();
        MSearch = new javax.swing.JLabel();
        Addproduct = new javax.swing.JPanel();
        AddPro = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Order = new javax.swing.JPanel();
        order = new javax.swing.JLabel();
        Jpanal11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanal10.setBackground(new java.awt.Color(227, 236, 222));
        Jpanal10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Createaccount.setBackground(new java.awt.Color(255, 255, 255));
        Createaccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Createaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateaccountMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreateaccountMousePressed(evt);
            }
        });

        Account.setBackground(new java.awt.Color(139, 193, 147));
        Account.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/account.png"))); // NOI18N
        Account.setText("Create Account ");
        Account.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout CreateaccountLayout = new javax.swing.GroupLayout(Createaccount);
        Createaccount.setLayout(CreateaccountLayout);
        CreateaccountLayout.setHorizontalGroup(
            CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateaccountLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Account)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CreateaccountLayout.setVerticalGroup(
            CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateaccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(Createaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 80));

        SearchM.setBackground(new java.awt.Color(255, 255, 255));
        SearchM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SearchM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMMousePressed(evt);
            }
        });

        MSearch.setBackground(new java.awt.Color(255, 255, 255));
        MSearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        MSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/search.png"))); // NOI18N
        MSearch.setText("Search and Update");

        javax.swing.GroupLayout SearchMLayout = new javax.swing.GroupLayout(SearchM);
        SearchM.setLayout(SearchMLayout);
        SearchMLayout.setHorizontalGroup(
            SearchMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchMLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(MSearch)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        SearchMLayout.setVerticalGroup(
            SearchMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MSearch)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(SearchM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 90));

        Addproduct.setBackground(new java.awt.Color(255, 255, 255));
        Addproduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Addproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddproductMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddproductMousePressed(evt);
            }
        });

        AddPro.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        AddPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/addproduct.png"))); // NOI18N
        AddPro.setText("Add Product");

        javax.swing.GroupLayout AddproductLayout = new javax.swing.GroupLayout(Addproduct);
        Addproduct.setLayout(AddproductLayout);
        AddproductLayout.setHorizontalGroup(
            AddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddproductLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AddPro)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        AddproductLayout.setVerticalGroup(
            AddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddproductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddPro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Addproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 80));

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/logout.png"))); // NOI18N
        jLabel1.setText("Logout");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 270, 70));

        Order.setBackground(new java.awt.Color(255, 255, 255));
        Order.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OrderMousePressed(evt);
            }
        });
        Order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        order.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/order.png"))); // NOI18N
        order.setText("Take Order");
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderMousePressed(evt);
            }
        });
        Order.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 60));

        jPanel1.add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 270, 80));

        Jpanal10.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 690));

        Jpanal11.setBackground(new java.awt.Color(191, 191, 191));
        Jpanal11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/applelogin.png"))); // NOI18N
        jLabel5.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel6.setText("APPLE iSTORE");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("WELCOME MANAGER");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/click.png"))); // NOI18N
        jLabel4.setText("Click The Icon What You Want To Do");

        javax.swing.GroupLayout Jpanal11Layout = new javax.swing.GroupLayout(Jpanal11);
        Jpanal11.setLayout(Jpanal11Layout);
        Jpanal11Layout.setHorizontalGroup(
            Jpanal11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanal11Layout.createSequentialGroup()
                .addGroup(Jpanal11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanal11Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jpanal11Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel2))
                    .addGroup(Jpanal11Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jpanal11Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        Jpanal11Layout.setVerticalGroup(
            Jpanal11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanal11Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        Jpanal10.add(Jpanal11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1080, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanal10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanal10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateaccountMouseClicked
        CreateAccount1 CA=new CreateAccount1();
      
        Jpanal11.removeAll();
        Jpanal11.add(CA).setVisible(true);
    }//GEN-LAST:event_CreateaccountMouseClicked

    private void CreateaccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateaccountMousePressed
        Createaccount.setBackground(ClickedColor);
        SearchM.setBackground(DefaultColor);
        Addproduct.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
    }//GEN-LAST:event_CreateaccountMousePressed

    private void SearchMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMMouseClicked
        SearchproductM SPM=new  SearchproductM();
        Jpanal11.removeAll();
        Jpanal11.add(SPM).setVisible(true);
    }//GEN-LAST:event_SearchMMouseClicked

    private void SearchMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMMousePressed
        Createaccount.setBackground(DefaultColor);
        SearchM.setBackground(ClickedColor);
        Addproduct.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
    }//GEN-LAST:event_SearchMMousePressed

    private void AddproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddproductMouseClicked

        Addproduct AP=new Addproduct();
        Jpanal11.removeAll();
        Jpanal11.add(AP).setVisible(true);
    }//GEN-LAST:event_AddproductMouseClicked

    private void AddproductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddproductMousePressed
        Createaccount.setBackground(DefaultColor);
        SearchM.setBackground(DefaultColor);
        Addproduct.setBackground(ClickedColor);
        Logout.setBackground(DefaultColor);
    }//GEN-LAST:event_AddproductMousePressed

    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        Createaccount.setBackground(DefaultColor);
        SearchM.setBackground(DefaultColor);
        Addproduct.setBackground(DefaultColor);
        Logout.setBackground(ClickedColor);
    }//GEN-LAST:event_LogoutMousePressed

    private void orderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMousePressed

    }//GEN-LAST:event_orderMousePressed

    private void OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseClicked
        Placeorder1 PO = new Placeorder1();
       Jpanal11.removeAll();
   Jpanal11.add(PO).setVisible(true);
    }//GEN-LAST:event_OrderMouseClicked

    private void OrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMousePressed
        SearchM.setBackground(DefaultColor);
        Order.setBackground(ClickedColor);
        Logout.setBackground(DefaultColor);
    }//GEN-LAST:event_OrderMousePressed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        dispose();
    Loginform lg = new Loginform();
    lg.setVisible(true);

        
    }//GEN-LAST:event_LogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JLabel AddPro;
    private javax.swing.JPanel Addproduct;
    private javax.swing.JPanel Createaccount;
    private javax.swing.JPanel Jpanal10;
    private javax.swing.JPanel Jpanal11;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel MSearch;
    private javax.swing.JPanel Order;
    private javax.swing.JPanel SearchM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel order;
    // End of variables declaration//GEN-END:variables
}
