/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ManagerController;
import Controller.ProductController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Kidurshalini
 */
public class SearchproductM extends javax.swing.JInternalFrame {
        ManagerController manager; 
        ProductController ProductController;
            Connection con=null;
            PreparedStatement pstmt=null;
           
           
            String SUrl="jdbc:MySQL://localhost:3306/stock_management_system";
            String SUser="root";
            String SPass="";
            
            String Modelname1,Product1,Colour1,Storage1,unitprice1,P_ID;
             int Price,Quantity1;
     
     
    public SearchproductM() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        ui.setEastPane(null);
        ui.setSouthPane(null);
        ui.setWestPane(null);
        manager = new ManagerController(this);
        ProductController=new ProductController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SModel = new javax.swing.JTextField();
        Productsearch = new javax.swing.JButton();
        Viewall = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtUQuantity = new javax.swing.JTextField();
        txtUPrice = new javax.swing.JTextField();
        txtUStorage = new javax.swing.JTextField();
        txtUcolour = new javax.swing.JTextField();
        txtUmodel = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        UProduct = new javax.swing.JComboBox<>();
        SProduct = new javax.swing.JComboBox<>();
        Productupdate1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewtbl = new javax.swing.JTable();
        txtUid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CashirP_Clear = new javax.swing.JButton();
        CADelete = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(140, 690));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Product Name:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Model Name:");

        SModel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SModel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SModelActionPerformed(evt);
            }
        });

        Productsearch.setBackground(new java.awt.Color(255, 255, 255));
        Productsearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Productsearch.setForeground(new java.awt.Color(0, 0, 102));
        Productsearch.setText("SEARCH");
        Productsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsearchActionPerformed(evt);
            }
        });

        Viewall.setBackground(new java.awt.Color(255, 255, 255));
        Viewall.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Viewall.setForeground(new java.awt.Color(0, 0, 102));
        Viewall.setText("VIEW ALL");
        Viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewallActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Not compulsary");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Model name:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Product Name:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Colour:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Storage details:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Price:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Quantity:");

        txtUQuantity.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUQuantityActionPerformed(evt);
            }
        });

        txtUPrice.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUPriceActionPerformed(evt);
            }
        });

        txtUStorage.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUStorage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUStorageActionPerformed(evt);
            }
        });

        txtUcolour.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUcolour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUcolour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUcolourActionPerformed(evt);
            }
        });

        txtUmodel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUmodel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmodelActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Update Product Details");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Search Product Details");

        UProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mac ", "I-phone", "Airpods", "I-Watchs" }));
        UProduct.setBorder(null);

        SProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mac ", "I-phone", "Airpods", "I-Watchs" }));
        SProduct.setBorder(null);

        Productupdate1.setBackground(new java.awt.Color(255, 255, 255));
        Productupdate1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Productupdate1.setForeground(new java.awt.Color(0, 0, 102));
        Productupdate1.setText("UPDATE");
        Productupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productupdate1ActionPerformed(evt);
            }
        });

        viewtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_ID", "Product_Name", "Model_Name", "Colour", "Storage", "Quantity", "Unit_Price", "Total_Price"
            }
        ));
        viewtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewtblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(viewtbl);

        txtUid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUidActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Product_ID");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        CashirP_Clear.setBackground(new java.awt.Color(255, 204, 204));
        CashirP_Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CashirP_Clear.setForeground(new java.awt.Color(255, 51, 51));
        CashirP_Clear.setText("CLEAR");
        CashirP_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashirP_ClearActionPerformed(evt);
            }
        });

        CADelete.setBackground(new java.awt.Color(255, 204, 204));
        CADelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CADelete.setForeground(new java.awt.Color(255, 0, 0));
        CADelete.setText("DELETE");
        CADelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(CashirP_Clear)
                        .addGap(245, 245, 245)
                        .addComponent(Productupdate1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUStorage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(534, 534, 534)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                            .addComponent(txtUQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtUPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(SProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(SModel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(123, 123, 123)
                                            .addComponent(Productsearch)))
                                    .addGap(127, 127, 127)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtUcolour, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel12))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtUid, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(96, 96, 96))
                                                .addComponent(txtUmodel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(UProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Viewall)
                                    .addGap(73, 73, 73)
                                    .addComponent(CADelete))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel6)
                        .addComponent(SProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(UProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtUmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtUcolour, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addComponent(txtUQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Productupdate1)
                            .addComponent(CashirP_Clear)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(SModel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Productsearch)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Viewall)
                    .addComponent(CADelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SModelActionPerformed

    private void ProductsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsearchActionPerformed
        if (SProduct.getSelectedItem() != null || !SModel.getText().isEmpty()) {
        String getProduct = SProduct.getSelectedItem().toString();
        String query;

        if (!SModel.getText().isEmpty()) {
            query = "SELECT Product_ID, Product_Name, Model_Name, Colour, Storage, Quantity, Unit_Price, Total_Price FROM product_details WHERE Product_Name=? AND Model_Name=?";
        } else {
            query = "SELECT Product_ID, Product_Name, Model_Name, Colour, Storage, Quantity, Unit_Price, Total_Price FROM product_details WHERE Product_Name=?";
        }

        DefaultTableModel table = (DefaultTableModel) viewtbl.getModel();
        ProductController.Searchproduct(table, getProduct, SModel.getText(), query);
    }

    }//GEN-LAST:event_ProductsearchActionPerformed

    private void ViewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewallActionPerformed

         String query = "select * from  product_details";  
         DefaultTableModel table = (DefaultTableModel) viewtbl.getModel();
         manager.view(query,table);
    }//GEN-LAST:event_ViewallActionPerformed

    private void txtUQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUQuantityActionPerformed

    private void txtUPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUPriceActionPerformed

    private void txtUStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUStorageActionPerformed

    private void txtUcolourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUcolourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUcolourActionPerformed

    private void txtUmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmodelActionPerformed

    private void Productupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productupdate1ActionPerformed
         try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection(SUrl,SUser,SPass);
                
                P_ID=txtUid.getText();
                String getProduct=UProduct.getSelectedItem().toString();
                Modelname1=txtUmodel.getText();
                Colour1= txtUcolour.getText();
                Storage1=txtUStorage.getText();
                Price=Integer.parseInt(txtUPrice.getText());
                Quantity1=Integer.parseInt(txtUQuantity.getText());
                 double gettotal = manager.getTotal(Price, Quantity1);
                String total = String.valueOf(gettotal);
                String query="UPDATE product_details SET Product_ID=?,Product_Name=?,Model_Name=?,Colour=?,Storage=?,Quantity=?,Unit_Price=?,Total_Price=? WHERE Product_ID=?";	
                pstmt=con.prepareStatement(query);
                 pstmt.setString(1,P_ID);
                 pstmt.setString(2,getProduct);
                 pstmt.setString(3,Modelname1);
                 pstmt.setString(4,Colour1);
                 pstmt.setString(5,Storage1);
                 pstmt.setInt(6,Quantity1);
                 pstmt.setInt(7,Price);
                    pstmt.setDouble(8, gettotal);
                 pstmt.setString(9,P_ID);
          
             int rowsUpdate=pstmt.executeUpdate();
                if(rowsUpdate>0){
                    JOptionPane.showMessageDialog(null,"Updated");
                }else{
               JOptionPane.showMessageDialog(null,"No record founded");
           }
                 }catch(Exception e){
                
                 JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_Productupdate1ActionPerformed

    private void viewtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewtblMouseClicked
       DefaultTableModel model=(DefaultTableModel) viewtbl.getModel();
       
        txtUid.setText(model.getValueAt( viewtbl.getSelectedRow(),0).toString());
        UProduct.setSelectedItem(model.getValueAt(viewtbl.getSelectedRow(), 1).toString());
        txtUmodel.setText(model.getValueAt( viewtbl.getSelectedRow(),2).toString());
        txtUcolour.setText(model.getValueAt( viewtbl.getSelectedRow(),3).toString());
        txtUStorage.setText(model.getValueAt( viewtbl.getSelectedRow(),4).toString());
        txtUPrice.setText(model.getValueAt( viewtbl.getSelectedRow(),6).toString());
        txtUQuantity.setText(model.getValueAt( viewtbl.getSelectedRow(),5).toString());
   
      
    }//GEN-LAST:event_viewtblMouseClicked

    private void txtUidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUidActionPerformed

    private void CashirP_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashirP_ClearActionPerformed
                   txtUmodel.setText("");
                   SModel.setText("");
                  txtUPrice.setText("");
                   txtUQuantity.setText("");
                   txtUStorage.setText("");
                   txtUcolour.setText("");
                  txtUid.setText("");
                 
    }//GEN-LAST:event_CashirP_ClearActionPerformed

    private void CADeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADeleteActionPerformed

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);

            String query = "DELETE FROM product_details WHERE Product_ID=?";
            
            pstmt = con.prepareStatement(query);
            pstmt.setString(1, txtUid.getText());
            pstmt.executeUpdate();

            pstmt.close();


            JOptionPane.showMessageDialog(null, "Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_CADeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CADelete;
    private javax.swing.JButton CashirP_Clear;
    private javax.swing.JButton Productsearch;
    private javax.swing.JButton Productupdate1;
    private javax.swing.JTextField SModel;
    private javax.swing.JComboBox<String> SProduct;
    private javax.swing.JComboBox<String> UProduct;
    private javax.swing.JButton Viewall;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtUPrice;
    private javax.swing.JTextField txtUQuantity;
    private javax.swing.JTextField txtUStorage;
    private javax.swing.JTextField txtUcolour;
    private javax.swing.JTextField txtUid;
    private javax.swing.JTextField txtUmodel;
    private javax.swing.JTable viewtbl;
    // End of variables declaration//GEN-END:variables
}
